server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  message:
    basename: message
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"